/**
 * Automatically translated from C++ to Java
 * 
 * Original file: include/InventoryService.h
 * Module: InventoryService
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.service;

import com.example.models.Product;
import com.example.models.Order;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Service
public class InventoryService {
    private final Map<Integer, Product> products = new HashMap<>();
    private final Map<Integer, Order> orders = new HashMap<>();
    private int nextProductId = 1;
    private int nextOrderId = 1;

    // Constructor
    public InventoryService() {
    }

    // Product operations
    public Product addProduct(String name, String category, double price, int quantity) {
        Product product = new Product(nextProductId++, name, category, price, quantity);
        products.put(product.getId(), product);
        return product;
    }

    public Product getProduct(int id) {
        return products.get(id);
    }

    public List<Product> getAllProducts() {
        return new ArrayList<>(products.values());
    }

    public List<Product> getProductsByCategory(String category) {
        List<Product> result = new ArrayList<>();
        for (Product product : products.values()) {
            if (product.getCategory().equalsIgnoreCase(category)) {
                result.add(product);
            }
        }
        return result;
    }

    public boolean updateProductQuantity(int id, int quantity) {
        Product product = products.get(id);
        if (product != null) {
            product.setQuantity(quantity);
            return true;
        }
        return false;
    }

    public boolean deleteProduct(int id) {
        return products.remove(id) != null;
    }

    // Order operations
    public Order createOrder(String customerName) {
        Order order = new Order(nextOrderId++, customerName);
        orders.put(order.getId(), order);
        return order;
    }

    public boolean addItemToOrder(int orderId, int productId, int quantity) {
        Order order = orders.get(orderId);
        Product product = products.get(productId);
        if (order != null && product != null && product.getQuantity() >= quantity) {
            order.addItem(product, quantity);
            product.setQuantity(product.getQuantity() - quantity);
            return true;
        }
        return false;
    }

    public Order getOrder(int id) {
        return orders.get(id);
    }

    public List<Order> getAllOrders() {
        return new ArrayList<>(orders.values());
    }

    public boolean completeOrder(int orderId) {
        Order order = orders.get(orderId);
        if (order != null) {
            order.setCompleted(true);
            return true;
        }
        return false;
    }

    public boolean cancelOrder(int orderId) {
        Order order = orders.get(orderId);
        if (order != null) {
            for (Map.Entry<Product, Integer> entry : order.getItems().entrySet()) {
                Product product = entry.getKey();
                int quantity = entry.getValue();
                product.setQuantity(product.getQuantity() + quantity);
            }
            orders.remove(orderId);
            return true;
        }
        return false;
    }

    // Analytics
    public double getTotalInventoryValue() {
        double totalValue = 0.0;
        for (Product product : products.values()) {
            totalValue += product.getPrice() * product.getQuantity();
        }
        return totalValue;
    }

    public int getTotalProductCount() {
        return products.size();
    }

    public Map<String, Integer> getProductCountByCategory() {
        Map<String, Integer> categoryCount = new HashMap<>();
        for (Product product : products.values()) {
            categoryCount.put(product.getCategory(), categoryCount.getOrDefault(product.getCategory(), 0) + 1);
        }
        return categoryCount;
    }

    // Display
    public void displayAllProducts() {
        for (Product product : products.values()) {
            System.out.println(product);
        }
    }

    public void displayAllOrders() {
        for (Order order : orders.values()) {
            System.out.println(order);
        }
    }
}