/**
 * Automatically translated from C++ to Java
 * 
 * Original file: src/main.cpp
 * Module: main
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp;

import com.example.inventory.service.InventoryService;
import com.example.inventory.util.Utils;
import com.example.inventory.model.Product;
import com.example.inventory.model.Order;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.util.List;
import java.util.Map;

@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(InventoryManagementApplication.class, args);

        System.out.println("\n");
        System.out.println("╔════════════════════════════════════════════════════════════╗");
        System.out.println("║     INVENTORY MANAGEMENT SYSTEM - TEST SUITE              ║");
        System.out.println("╚════════════════════════════════════════════════════════════╝");

        InventoryService service = new InventoryService();

        // Run all tests
        testProductOperations(service);
        testOrderOperations(service);
        testAnalytics(service);
        testUtilities();
        testOrderCancellation(service);

        printSeparator();
        System.out.println("All tests completed successfully!");
        System.out.println("Timestamp: " + Utils.getCurrentTimestamp());
        printSeparator();
    }

    private static void printSeparator() {
        System.out.println("\n" + "=".repeat(60) + "\n");
    }

    private static void testProductOperations(InventoryService service) {
        System.out.println("TEST 1: Product Operations");
        printSeparator();

        // Add products
        service.addProduct("Laptop", "Electronics", 999.99, 10);
        service.addProduct("Mouse", "Electronics", 29.99, 50);
        service.addProduct("Keyboard", "Electronics", 79.99, 30);
        service.addProduct("Desk Chair", "Furniture", 199.99, 15);
        service.addProduct("Desk Lamp", "Furniture", 49.99, 25);

        System.out.println("Added 5 products to inventory");
        service.displayAllProducts();

        // Get product by ID
        System.out.println("\nRetrieving product ID 1:");
        Product laptop = service.getProduct(1);
        if (laptop != null) {
            laptop.display();
            System.out.println("JSON: " + laptop.toJson());
        }

        // Get products by category
        System.out.println("\nProducts in Electronics category:");
        List<Product> electronics = service.getProductsByCategory("Electronics");
        for (Product product : electronics) {
            product.display();
        }
    }

    private static void testOrderOperations(InventoryService service) {
        printSeparator();
        System.out.println("TEST 2: Order Operations");
        printSeparator();

        // Create order 1
        Order order1 = service.createOrder("John Doe");
        if (order1 != null) {
            System.out.println("Created order #" + order1.getId() + " for " + order1.getCustomerName());

            service.addItemToOrder(order1.getId(), 1, 2);  // 2 Laptops
            service.addItemToOrder(order1.getId(), 2, 3);  // 3 Mice

            order1.display();
            System.out.println("JSON: " + order1.toJson());
        }

        // Create order 2
        Order order2 = service.createOrder("Jane Smith");
        if (order2 != null) {
            System.out.println("\nCreated order #" + order2.getId() + " for " + order2.getCustomerName());

            service.addItemToOrder(order2.getId(), 4, 1);  // 1 Desk Chair
            service.addItemToOrder(order2.getId(), 5, 2);  // 2 Desk Lamps

            order2.display();
        }

        // Complete first order
        System.out.println("\nCompleting order #1...");
        service.completeOrder(1);

        service.displayAllOrders();
    }

    private static void testAnalytics(InventoryService service) {
        printSeparator();
        System.out.println("TEST 3: Analytics");
        printSeparator();

        double totalValue = service.getTotalInventoryValue();
        int totalCount = service.getTotalProductCount();

        System.out.println("Total Inventory Value: " + Utils.formatCurrency(totalValue));
        System.out.println("Total Product Count: " + totalCount + " items");

        System.out.println("\nProducts by Category:");
        Map<String, Integer> categoryCount = service.getProductCountByCategory();
        for (Map.Entry<String, Integer> entry : categoryCount.entrySet()) {
            System.out.println("  " + entry.getKey() + ": " + entry.getValue() + " items");
        }
    }

    private static void testUtilities() {
        printSeparator();
        System.out.println("TEST 4: Utility Functions");
        printSeparator();

        String testStr = "  Hello World  ";
        System.out.println("Original: '" + testStr + "'");
        System.out.println("Trimmed: '" + Utils.trim(testStr) + "'");
        System.out.println("Uppercase: '" + Utils.toUpperCase(Utils.trim(testStr)) + "'");
        System.out.println("Lowercase: '" + Utils.toLowerCase(Utils.trim(testStr)) + "'");

        double price = 100.0;
        System.out.println("\nPrice calculations:");
        System.out.println("Original price: " + Utils.formatCurrency(price));
        System.out.println("After 20% discount: " + Utils.formatCurrency(Utils.calculateDiscount(price, 20.0)));
        System.out.println("Tax (8%): " + Utils.formatCurrency(Utils.calculateTax(price, 8.0)));

        System.out.println("\nCurrent timestamp: " + Utils.getCurrentTimestamp());

        System.out.println("\nValidation tests:");
        System.out.println("Is 'AB' valid product name? " + (Utils.isValidProductName("AB") ? "Yes" : "No"));
        System.out.println("Is 'A' valid product name? " + (Utils.isValidProductName("A") ? "Yes" : "No"));
        System.out.println("Is price -10 valid? " + (Utils.isValidPrice(-10.0) ? "Yes" : "No"));
        System.out.println("Is quantity -5 valid? " + (Utils.isValidQuantity(-5) ? "Yes" : "No"));
    }

    private static void testOrderCancellation(InventoryService service) {
        printSeparator();
        System.out.println("TEST 5: Order Cancellation (Inventory Restoration)");
        printSeparator();

        System.out.println("Inventory before order:");
        Product keyboard = service.getProduct(3);
        if (keyboard != null) {
            System.out.println("Keyboard quantity: " + keyboard.getQuantity());
        }

        Order order3 = service.createOrder("Bob Johnson");
        if (order3 != null) {
            System.out.println("\nCreating and then cancelling order #" + order3.getId());
            service.addItemToOrder(order3.getId(), 3, 5);  // 5 Keyboards

            order3.display();

            System.out.println("\nKeyboard quantity after order: " + keyboard.getQuantity());

            System.out.println("\nCancelling order...");
            service.cancelOrder(order3.getId());

            System.out.println("Keyboard quantity after cancellation: " + keyboard.getQuantity());
        }
    }
}