/**
 * Automatically translated from C++ to Java
 * 
 * Original file: include/Product.h
 * Module: Product
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp;

import jakarta.jms.*;
import com.ibm.mq.jms.*;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(ProductApplication.class, args);
    }
}

class Product {
    private int id;
    private String name;
    private String category;
    private double price;
    private int quantity;

    // Default constructor
    public Product() {
    }

    // Parameterized constructor
    public Product(int id, String name, String category, double price, int quantity) {
        this.id = id;
        this.name = name;
        this.category = category;
        this.price = price;
        this.quantity = quantity;
    }

    // Getters
    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getCategory() {
        return category;
    }

    public double getPrice() {
        return price;
    }

    public int getQuantity() {
        return quantity;
    }

    // Setters
    public void setId(int id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    // Business methods
    public boolean isInStock() {
        return quantity > 0;
    }

    public double getTotalValue() {
        return price * quantity;
    }

    public void updateQuantity(int change) {
        this.quantity += change;
    }

    // Display method
    public void display() {
        System.out.println("Product ID: " + id);
        System.out.println("Name: " + name);
        System.out.println("Category: " + category);
        System.out.println("Price: $" + price);
        System.out.println("Quantity: " + quantity);
    }

    // Convert to JSON string
    public String toJson() {
        return String.format("{\"id\":%d,\"name\":\"%s\",\"category\":\"%s\",\"price\":%.2f,\"quantity\":%d}",
                id, name, category, price, quantity);
    }
}