/**
 * Automatically translated from C++ to Java
 * 
 * Original file: src/InventoryService.cpp
 * Module: InventoryService
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp;

import jakarta.jms.*;
import com.ibm.mq.jms.*;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.stereotype.Service;

import java.util.*;
import java.util.stream.Collectors;

@SpringBootApplication
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(InventoryServiceApplication.class, args);
    }
}

@Service
public class InventoryService {

    private int nextProductId = 1;
    private int nextOrderId = 1;
    private final Map<Integer, Product> products = new HashMap<>();
    private final Map<Integer, Order> orders = new HashMap<>();

    // Product operations
    public Product addProduct(String name, String category, double price, int quantity) {
        Product product = new Product(nextProductId, name, category, price, quantity);
        products.put(nextProductId, product);
        nextProductId++;
        return product;
    }

    public Product getProduct(int id) {
        return products.get(id);
    }

    public List<Product> getAllProducts() {
        return new ArrayList<>(products.values());
    }

    public List<Product> getProductsByCategory(String category) {
        return products.values().stream()
                .filter(product -> product.getCategory().equals(category))
                .collect(Collectors.toList());
    }

    public boolean updateProductQuantity(int id, int quantity) {
        Product product = getProduct(id);
        if (product != null) {
            product.setQuantity(quantity);
            return true;
        }
        return false;
    }

    public boolean deleteProduct(int id) {
        return products.remove(id) != null;
    }

    // Order operations
    public Order createOrder(String customerName) {
        Order order = new Order(nextOrderId, customerName);
        orders.put(nextOrderId, order);
        nextOrderId++;
        return order;
    }

    public boolean addItemToOrder(int orderId, int productId, int quantity) {
        Order order = getOrder(orderId);
        Product product = getProduct(productId);

        if (order == null || product == null) {
            return false;
        }

        if (product.getQuantity() < quantity) {
            System.out.println("Error: Insufficient stock for product " + product.getName());
            return false;
        }

        OrderItem item = new OrderItem(productId, product.getName(), quantity, product.getPrice());
        order.addItem(item);
        product.updateQuantity(-quantity);

        return true;
    }

    public Order getOrder(int id) {
        return orders.get(id);
    }

    public List<Order> getAllOrders() {
        return new ArrayList<>(orders.values());
    }

    public boolean completeOrder(int orderId) {
        Order order = getOrder(orderId);
        if (order != null && "PENDING".equals(order.getStatus())) {
            order.setStatus("COMPLETED");
            return true;
        }
        return false;
    }

    public boolean cancelOrder(int orderId) {
        Order order = getOrder(orderId);
        if (order != null && "PENDING".equals(order.getStatus())) {
            // Restore inventory
            for (OrderItem item : order.getItems()) {
                Product product = getProduct(item.getProductId());
                if (product != null) {
                    product.updateQuantity(item.getQuantity());
                }
            }
            order.setStatus("CANCELLED");
            return true;
        }
        return false;
    }

    // Analytics
    public double getTotalInventoryValue() {
        return products.values().stream()
                .mapToDouble(Product::getTotalValue)
                .sum();
    }

    public int getTotalProductCount() {
        return products.values().stream()
                .mapToInt(Product::getQuantity)
                .sum();
    }

    public Map<String, Integer> getProductCountByCategory() {
        Map<String, Integer> categoryCount = new HashMap<>();
        for (Product product : products.values()) {
            categoryCount.merge(product.getCategory(), product.getQuantity(), Integer::sum);
        }
        return categoryCount;
    }

    // Display
    public void displayAllProducts() {
        System.out.println("\n=== All Products ===");
        products.values().forEach(Product::display);
    }

    public void displayAllOrders() {
        System.out.println("\n=== All Orders ===");
        orders.values().forEach(Order::display);
    }
}

// Assume Product, Order, and OrderItem classes are defined with necessary fields and methods.