/**
 * Automatically translated from C++ to Java
 * 
 * Original file: src/Utils.cpp
 * Module: Utils
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.utils;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.StringTokenizer;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

public class Utils {

    // String utilities
    public static String toUpperCase(String str) {
        if (str == null) {
            return null;
        }
        return str.toUpperCase(Locale.ROOT);
    }

    public static String toLowerCase(String str) {
        if (str == null) {
            return null;
        }
        return str.toLowerCase(Locale.ROOT);
    }

    public static String trim(String str) {
        if (str == null) {
            return null;
        }
        return str.trim();
    }

    public static List<String> split(String str, char delimiter) {
        List<String> tokens = new ArrayList<>();
        if (str == null) {
            return tokens;
        }
        StringTokenizer tokenizer = new StringTokenizer(str, String.valueOf(delimiter));
        while (tokenizer.hasMoreTokens()) {
            tokens.add(tokenizer.nextToken());
        }
        return tokens;
    }

    // Validation utilities
    public static boolean isValidPrice(double price) {
        return price >= 0.0;
    }

    public static boolean isValidQuantity(int quantity) {
        return quantity >= 0;
    }

    public static boolean isValidProductName(String name) {
        return name != null && !name.isEmpty() && name.length() >= 2 && name.length() <= 100;
    }

    // Formatting utilities
    public static String formatCurrency(double amount) {
        DecimalFormat decimalFormat = new DecimalFormat("$#.00");
        return decimalFormat.format(amount);
    }

    public static String getCurrentTimestamp() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        return dateFormat.format(new Date());
    }

    // Math utilities
    public static double calculateDiscount(double price, double percentage) {
        if (percentage < 0.0 || percentage > 100.0) {
            return price;
        }
        return price * (1.0 - percentage / 100.0);
    }

    public static double calculateTax(double amount, double taxRate) {
        return amount * (taxRate / 100.0);
    }
}