/**
 * Automatically translated from C++ to Java
 * 
 * Original file: include/Utils.h
 * Module: Utils
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.utils;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.StringTokenizer;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

public class Utils {

    // String utilities
    public static String toUpperCase(String str) {
        if (str == null) {
            return null;
        }
        return str.toUpperCase(Locale.ROOT);
    }

    public static String toLowerCase(String str) {
        if (str == null) {
            return null;
        }
        return str.toLowerCase(Locale.ROOT);
    }

    public static String trim(String str) {
        if (str == null) {
            return null;
        }
        return str.trim();
    }

    public static List<String> split(String str, char delimiter) {
        List<String> result = new ArrayList<>();
        if (str == null) {
            return result;
        }
        StringTokenizer tokenizer = new StringTokenizer(str, String.valueOf(delimiter));
        while (tokenizer.hasMoreTokens()) {
            result.add(tokenizer.nextToken());
        }
        return result;
    }

    // Validation utilities
    public static boolean isValidPrice(double price) {
        return price >= 0;
    }

    public static boolean isValidQuantity(int quantity) {
        return quantity >= 0;
    }

    public static boolean isValidProductName(String name) {
        return name != null && !name.trim().isEmpty();
    }

    // Formatting utilities
    public static String formatCurrency(double amount) {
        NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(Locale.US);
        return currencyFormat.format(amount);
    }

    public static String getCurrentTimestamp() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        return sdf.format(new Date());
    }

    // Math utilities
    public static double calculateDiscount(double price, double percentage) {
        if (price < 0 || percentage < 0) {
            throw new IllegalArgumentException("Price and percentage must be non-negative");
        }
        return price * (percentage / 100);
    }

    public static double calculateTax(double amount, double taxRate) {
        if (amount < 0 || taxRate < 0) {
            throw new IllegalArgumentException("Amount and tax rate must be non-negative");
        }
        return amount * (taxRate / 100);
    }
}