/**
 * Automatically translated from C++ to Java
 * 
 * Original file: include/Order.h
 * Module: Order
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;

public class OrderItem {
    private int productId;
    private String productName;
    private int quantity;
    private double unitPrice;

    public OrderItem(int productId, String productName, int quantity, double unitPrice) {
        this.productId = productId;
        this.productName = productName;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
    }

    public double getSubtotal() {
        return quantity * unitPrice;
    }

    public String toJson() {
        return String.format("{\"productId\":%d,\"productName\":\"%s\",\"quantity\":%d,\"unitPrice\":%.2f}",
                productId, productName, quantity, unitPrice);
    }

    // Getters and Setters
    public int getProductId() {
        return productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public double getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(double unitPrice) {
        this.unitPrice = unitPrice;
    }
}

public class Order {
    private int id;
    private String customerName;
    private List<OrderItem> items;
    private String status;
    private Date orderDate;

    public Order() {
        this.items = new ArrayList<>();
        this.orderDate = new Date();
    }

    public Order(int id, String customerName) {
        this();
        this.id = id;
        this.customerName = customerName;
    }

    // Getters
    public int getId() {
        return id;
    }

    public String getCustomerName() {
        return customerName;
    }

    public String getStatus() {
        return status;
    }

    public List<OrderItem> getItems() {
        return items;
    }

    // Setters
    public void setStatus(String status) {
        this.status = status;
    }

    // Business methods
    public void addItem(OrderItem item) {
        items.add(item);
    }

    public double calculateTotal() {
        return items.stream().mapToDouble(OrderItem::getSubtotal).sum();
    }

    public int getTotalItems() {
        return items.size();
    }

    public void display() {
        System.out.println("Order ID: " + id);
        System.out.println("Customer Name: " + customerName);
        System.out.println("Status: " + status);
        System.out.println("Order Date: " + orderDate);
        System.out.println("Items:");
        items.forEach(item -> System.out.println(item.toJson()));
        System.out.println("Total: " + calculateTotal());
    }

    public String toJson() {
        String itemsJson = items.stream()
                .map(OrderItem::toJson)
                .collect(Collectors.joining(","));
        return String.format("{\"id\":%d,\"customerName\":\"%s\",\"status\":\"%s\",\"orderDate\":\"%s\",\"items\":[%s]}",
                id, customerName, status, orderDate, itemsJson);
    }
}