/**
 * Automatically translated from C++ to Java
 * 
 * Original file: src/Order.cpp
 * Module: Order
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.model;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonArrayBuilder;

public class OrderApplication {

    public static void main(String[] args) {
        // Entry point for the application
    }
}

// OrderItem class
class OrderItem {
    private final int productId;
    private final String productName;
    private final int quantity;
    private final double unitPrice;

    public OrderItem(int productId, String productName, int quantity, double unitPrice) {
        this.productId = productId;
        this.productName = productName;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
    }

    public double getSubtotal() {
        return quantity * unitPrice;
    }

    public JsonObject toJson() {
        return Json.createObjectBuilder()
                .add("productId", productId)
                .add("productName", productName)
                .add("quantity", quantity)
                .add("unitPrice", String.format("%.2f", unitPrice))
                .add("subtotal", String.format("%.2f", getSubtotal()))
                .build();
    }
}

// Order class
class Order {
    private final int id;
    private final String customerName;
    private String status;
    private final Instant orderDate;
    private final List<OrderItem> items;

    public Order() {
        this.id = 0;
        this.customerName = "";
        this.status = "PENDING";
        this.orderDate = Instant.now();
        this.items = new ArrayList<>();
    }

    public Order(int id, String customerName) {
        this.id = id;
        this.customerName = customerName;
        this.status = "PENDING";
        this.orderDate = Instant.now();
        this.items = new ArrayList<>();
    }

    public int getId() {
        return id;
    }

    public String getCustomerName() {
        return customerName;
    }

    public String getStatus() {
        return status;
    }

    public List<OrderItem> getItems() {
        return new ArrayList<>(items);
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public void addItem(OrderItem item) {
        items.add(item);
    }

    public double calculateTotal() {
        return items.stream().mapToDouble(OrderItem::getSubtotal).sum();
    }

    public int getTotalItems() {
        return items.stream().mapToInt(item -> item.quantity).sum();
    }

    public void display() {
        System.out.println("\n=== Order #" + id + " ===");
        System.out.println("Customer: " + customerName);
        System.out.println("Status: " + status);
        System.out.println("Items:");
        items.forEach(item -> System.out.println("  - " + item.productName 
                + " (x" + item.quantity + ") @ $" 
                + String.format("%.2f", item.unitPrice) 
                + " = $" + String.format("%.2f", item.getSubtotal())));
        System.out.println("Total: $" + String.format("%.2f", calculateTotal()));
    }

    public JsonObject toJson() {
        JsonArrayBuilder itemsArrayBuilder = Json.createArrayBuilder();
        items.forEach(item -> itemsArrayBuilder.add(item.toJson()));

        return Json.createObjectBuilder()
                .add("id", id)
                .add("customerName", customerName)
                .add("status", status)
                .add("totalItems", getTotalItems())
                .add("total", String.format("%.2f", calculateTotal()))
                .add("items", itemsArrayBuilder)
                .build();
    }
}