/**
 * Automatically translated from C++ to Java
 * 
 * Original file: src/Product.cpp
 * Module: Product
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.model;

import jakarta.annotation.PostConstruct;
import org.springframework.stereotype.Component;

import java.text.DecimalFormat;

@Component
public class Product {

    private int id;
    private String name;
    private String category;
    private double price;
    private int quantity;

    public Product() {
        this.id = 0;
        this.name = "";
        this.category = "";
        this.price = 0.0;
        this.quantity = 0;
    }

    public Product(int id, String name, String category, double price, int quantity) {
        this.id = id;
        this.name = name;
        this.category = category;
        this.price = price;
        this.quantity = quantity;
    }

    // Getters
    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getCategory() {
        return category;
    }

    public double getPrice() {
        return price;
    }

    public int getQuantity() {
        return quantity;
    }

    // Setters
    public void setId(int id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    // Business methods
    public boolean isInStock() {
        return quantity > 0;
    }

    public double getTotalValue() {
        return price * quantity;
    }

    public void updateQuantity(int change) {
        quantity += change;
        if (quantity < 0) {
            quantity = 0;
        }
    }

    public void display() {
        DecimalFormat df = new DecimalFormat("#.00");
        System.out.println("Product [ID: " + id 
                + ", Name: " + name 
                + ", Category: " + category 
                + ", Price: $" + df.format(price) 
                + ", Quantity: " + quantity + "]");
    }

    public String toJson() {
        DecimalFormat df = new DecimalFormat("#.00");
        return "{" +
                "\"id\":" + id +
                ",\"name\":\"" + name + "\"" +
                ",\"category\":\"" + category + "\"" +
                ",\"price\":" + df.format(price) +
                ",\"quantity\":" + quantity +
                ",\"inStock\":" + isInStock() +
                ",\"totalValue\":" + df.format(getTotalValue()) +
                "}";
    }
}